import{submitCryptoResearchCandidate,processCryptoResearchQueue,getCryptoResearchQueueState}from"./cryptoDeepResearchQueue.js";
import{listCryptoResearchRecords,getCryptoResearchRegistryStats}from"./cryptoResearchRegistry.js";
import buildCryptoBulkResearchContext from"./cryptoBulkResearchContext.js";
export async function runCryptoDeepResearchPipeline({candidates=[],concurrency=3,refreshFundamentals=false,refreshFinalIntelligence=false}={}){
  const startedAt=new Date().toISOString(),input=Array.isArray(candidates)?candidates:[],researchContext=await buildCryptoBulkResearchContext({refreshFundamentals,refreshFinalIntelligence});
  const submissions=input.map(c=>({symbol:c?.symbol??null,...submitCryptoResearchCandidate(c,{researchContext})})),processing=await processCryptoResearchQueue({concurrency}),records=listCryptoResearchRecords({limit:input.length||100}),approved=records.filter(r=>r?.approved===true),bot=records.filter(r=>r?.approved===true&&r?.candidateType==="CEX"&&r?.botHandoffAllowed===true),emerging=records.filter(r=>r?.candidateType==="EMERGING");
  return{approved:processing?.accepted===true,status:(processing?.failed??0)>0?"PARTIAL":"COMPLETE",submitted:submissions.filter(x=>x.accepted===true).length,rejectedSubmissions:submissions.filter(x=>x.accepted!==true).length,completed:processing?.completed??0,failed:processing?.failed??0,researchApproved:approved.length,cexBotHandoffReady:bot.length,emergingResearchOnly:emerging.length,botHandoffCandidates:bot,researchOnlyCandidates:emerging,bulkContext:{createdAt:researchContext?.createdAt??null,fundamentals:{fetchedAt:researchContext?.fundamentalSnapshot?.fetchedAt??null,providers:researchContext?.fundamentalSnapshot?.providers??{}},finalIntelligence:{fetchedAt:researchContext?.finalIntelligenceSnapshot?.fetchedAt??null,providers:researchContext?.finalIntelligenceSnapshot?.providers??{}}},submissions,records,registry:getCryptoResearchRegistryStats(),queue:getCryptoResearchQueueState(),startedAt,completedAt:new Date().toISOString()};
}
export default{runCryptoDeepResearchPipeline};
