import technical from"./cryptoTechnicalEngine.js";import fundamentals from"./cryptoProtocolFundamentalEngine.js";import tokenomics from"./cryptoTokenomicsEngine.js";import liquidity from"./cryptoLiquidityEngine.js";import marketStructure from"./cryptoMarketStructureEngine.js";import derivatives from"./cryptoDerivativesEngine.js";import onChain from"./cryptoOnChainEngine.js";import projectIntegrity from"./cryptoProjectIntegrityEngine.js";import socialNarrative from"./cryptoSocialNarrativeEngine.js";import events from"./cryptoEventIntelligenceEngine.js";import historical from"./cryptoHistoricalEngine.js";import marketRegime from"./cryptoMarketRegimeEngine.js";import score from"./cryptoResearchScorer.js";import buildSupporting from"../research/cryptoSupportingIntelligenceContext.js";import buildFinal from"../research/cryptoFinalIntelligenceContext.js";
const safe=async(n,fn)=>{try{return await fn();}catch(e){return{approved:false,engine:n,status:"ERROR",score:null,confidence:0,evidence:{},errors:[e instanceof Error?e.message:String(e)]};}};
export default async function run(c,{researchContext=null}={}){
  const fs=researchContext?.fundamentalSnapshot??null,fin=researchContext?.finalIntelligenceSnapshot??null,supporting=buildSupporting(c,fs),finalIntelligence=buildFinal(c,fin);
  const names=["technical","fundamentals","tokenomics","liquidity","marketStructure","derivatives","onChain","projectIntegrity","socialNarrative","events","historical","marketRegime"];
  const calls=[()=>technical(c),()=>fundamentals(c,{snapshot:fs}),()=>tokenomics(c),()=>liquidity(c),()=>marketStructure(c),()=>derivatives(c,{finalIntelligence}),()=>onChain(c,{supportingIntelligence:supporting}),()=>projectIntegrity(c,{supportingIntelligence:supporting}),()=>socialNarrative(c,{finalIntelligence}),()=>events(c,{finalIntelligence}),()=>historical(c,{supportingIntelligence:supporting}),()=>marketRegime(c)];
  const vals=await Promise.all(calls.map((fn,i)=>safe(names[i],fn))),engines=Object.fromEntries(names.map((n,i)=>[n,vals[i]]));
  return{approved:true,engine:"CRYPTO_RESEARCH_ORCHESTRATOR",status:"COMPLETE",engines,scoring:score(engines),intelligenceSources:{fundamentals:"SHARED_BULK_SNAPSHOT",supporting:"SHARED_BULK_SNAPSHOT",final:"SHARED_BULK_SNAPSHOT"},completedAt:new Date().toISOString()};
}
