import {AlertTriangle,Pause,Play,ShieldAlert,WalletCards,RefreshCw} from "lucide-react";
import {useCallback,useEffect,useState} from "react";
import BotSidebar from "../components/BotSidebar.jsx";
import {emergencyStopBot,getBotDashboard,pauseBot,resumeBot,setBotAllocation} from "../services/botApi.js";
import {getDedicatedAlpacaOverview} from "../services/botAlpacaApi.js";
import "./BotControls.css";
const money=v=>v==null?"—":new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v));
export default function BotControls(){
 const [sim,setSim]=useState(null),[alpaca,setAlpaca]=useState(null),[brokerError,setBrokerError]=useState(""),[amount,setAmount]=useState(""),[msg,setMsg]=useState(""),[err,setErr]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const [a,b]=await Promise.allSettled([getBotDashboard(),getDedicatedAlpacaOverview()]);if(a.status==="fulfilled"){setSim(a.value);setAmount(old=>old===""?String(a.value.account?.allocationUsd??""):old)}else setErr(a.reason?.message||"Simulator unavailable");if(b.status==="fulfilled"){setAlpaca(b.value);setBrokerError("")}else{setAlpaca(null);setBrokerError(b.reason?.message||"Broker data unavailable")}},[]);
 useEffect(()=>{load();const id=setInterval(load,15000);return()=>clearInterval(id)},[load]);
 const act=async(fn,success)=>{try{setBusy(true);setErr("");setMsg("");await fn();setMsg(success);await load()}catch(e){setErr(e.message)}finally{setBusy(false)}};
 const a=sim?.account||{},paused=Boolean(a.controls?.paused),running=Boolean(sim?.runtime?.running);
 return <div className="bot-app"><BotSidebar/><main className="bot-main controls-page"><header><div><span>CAPITAL & SAFETY</span><h1>Capital & Controls</h1><p>Dedicated Alpaca broker capital and independent internal simulator controls.</p></div><button className="bot-refresh" onClick={load}><RefreshCw size={14}/> Refresh</button></header>
 {err&&<div className="bot-error">{err}</div>}{msg&&<div className="control-ok">{msg}</div>}
 <section className="control-grid"><article><div className="control-title"><WalletCards/><div><span>DEDICATED BROKER · READ ONLY</span><h2>Alpaca Crypto Paper Capital</h2></div></div>{brokerError&&<div className="bot-error">{brokerError}</div>}
 <div className="allocation-stats"><div><span>Broker equity</span><b>{money(alpaca?.account?.equityUsd)}</b></div><div><span>Broker cash</span><b>{money(alpaca?.account?.cashUsd)}</b></div><div><span>Open positions</span><b>{alpaca?alpaca.positions.length:"—"}</b></div></div>
 <p>Broker-reported balance only. This page does not change Alpaca capital allocation or submit orders.</p><div className="control-safety-note"><ShieldAlert size={16}/> Alpaca automatic entries, exits and protective orders are not enabled.</div></article>
 <article><div className="control-title"><WalletCards/><div><span>INTERNAL SIMULATOR</span><h2>Simulator Capital Allocation</h2></div></div><p>This allocation applies only to simulated positions. It does not fund or limit Alpaca orders.</p><div className="allocation-stats"><div><span>Simulator equity</span><b>{money(a.equityUsd)}</b></div><div><span>Allocation</span><b>{money(a.allocationUsd)}</b></div><div><span>Available margin</span><b>{money(a.allocatedAvailableMarginUsd)}</b></div></div><label htmlFor="sim-amount">Simulator allocation (USD)</label><div className="allocation-input"><span>$</span><input id="sim-amount" type="number" min="1" step="1" value={amount} onChange={e=>setAmount(e.target.value)}/><button disabled={busy||!sim||!(Number(amount)>0)} onClick={()=>act(()=>setBotAllocation(amount),"Simulator allocation updated.")}>Apply</button></div><small>Existing simulator positions are not silently resized.</small></article>
 <article><div className="control-title"><ShieldAlert/><div><span>INTERNAL SIMULATOR ONLY</span><h2>Trading Runtime</h2></div></div><div className={`runtime-state ${paused||!running?"paused":"running"}`}><i/>{!sim?"UNAVAILABLE":!running?"RUNTIME OFFLINE":paused?"PAUSED":"RUNNING"}</div><p>Resume enables simulated new entries only when the internal runtime is actually running. Pausing prevents new simulator entries while existing simulator positions continue to be managed.</p><div className="control-actions">{paused?<button disabled={busy||!sim||!running} onClick={()=>act(resumeBot,"Simulator entries resumed.")}><Play/> Resume simulator</button>:<button disabled={busy||!sim} onClick={()=>act(pauseBot,"Simulator entries paused.")}><Pause/> Pause simulator</button>}<button className="emergency" disabled={busy||!sim} onClick={()=>{if(window.confirm("Pause and close ALL INTERNAL SIMULATOR positions? This does NOT affect Alpaca."))act(emergencyStopBot,"Simulator emergency stop requested.")}}><AlertTriangle/> Emergency stop simulator</button></div>{!running&&<p>The internal runtime is not running. Resume alone cannot start it; start the existing server runtime before resuming.</p>}</article></section></main></div>;
}
