import {Activity,BrainCircuit,CircleHelp,Gauge,ShieldCheck,TrendingUp,WalletCards,XCircle,RefreshCw,AlertTriangle} from 'lucide-react';
import {useCallback,useEffect,useState} from 'react';
import BotSidebar from '../components/BotSidebar.jsx';
import {closeBotPosition,getBotDashboard,getTradeExplanation} from '../services/botApi.js';
import {getDedicatedAlpacaOverview} from '../services/botAlpacaApi.js';
import './BotDashboard.css';
const n=v=>Number(v)||0;
const m=v=>v==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n(v));
const d=x=>x==='LONG'?'Bullish Direction':x==='SHORT'?'Bearish Direction':'—';
export default function BotDashboard(){
 const [x,setX]=useState(null),[alpaca,setAlpaca]=useState(null),[alpacaError,setAlpacaError]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(''),[ex,setEx]=useState(null),[tab,setTab]=useState('alpaca');
 const load=useCallback(async()=>{
   const results=await Promise.allSettled([getBotDashboard(),getDedicatedAlpacaOverview()]);
   if(results[0].status==='fulfilled'){setX(results[0].value);setErr('')}else setErr(results[0].reason?.message||'Internal ledger unavailable');
   if(results[1].status==='fulfilled'){setAlpaca(results[1].value);setAlpacaError('')}else {setAlpaca(null);setAlpacaError(results[1].reason?.message||'Dedicated Alpaca account unavailable')}
 },[]);
 useEffect(()=>{load();const id=setInterval(load,15000);return()=>clearInterval(id)},[load]);
 const explain=async id=>{try{setBusy(`ex-${id}`);setEx(await getTradeExplanation(id))}catch(e){setErr(e.message)}finally{setBusy('')}};
 const close=async q=>{if(!window.confirm(`Close ${q.symbol} INTERNAL simulator position?`))return;try{setBusy(`close-${q.id}`);await closeBotPosition(q.id);await load()}catch(e){setErr(e.message)}finally{setBusy('')}};
 const a=x?.account||{},p=a.positions||[],records=x?.memory?.records||[];
 return <div className="bot-app"><BotSidebar/><main className="bot-main">
  <header><div><span>AEMA INDEPENDENT CRYPTO BOT</span><h1>Trading Dashboard</h1><p>Dedicated broker-hosted paper account and separate historical simulator.</p></div><div className="bot-header-actions"><b className="bot-status"><i/>PAPER · AUTO EXECUTION DISABLED</b><button className="bot-refresh" onClick={load}><RefreshCw size={14}/>Refresh</button></div></header>
  {err&&<div className="bot-error">Internal ledger: {err}</div>}
  <nav className="bot-tabs"><button className={tab==='alpaca'?'active':''} onClick={()=>setTab('alpaca')}>Alpaca paper account</button><button className={tab==='internal'?'active':''} onClick={()=>setTab('internal')}>Internal simulator · history</button></nav>
  {tab==='alpaca'?<>
   {alpacaError&&<div className="bot-error"><AlertTriangle size={15}/>Dedicated account unavailable: {alpacaError}. Values are hidden rather than replaced with simulator balances.</div>}
   <div className="bot-provider"><div><strong>DEDICATED ALPACA CRYPTO PAPER</strong><small>{alpaca?.observedAt?`Last updated ${new Date(alpaca.observedAt).toLocaleTimeString()}`:'Waiting for broker data'}</small></div><span className={alpaca?'connected':'disconnected'}>{alpaca?'BROKER CONNECTED':'NOT VERIFIED'}</span></div>
   <section className="bot-kpis"><K i={WalletCards} l="Broker equity" v={m(alpaca?.account?.equityUsd)}/><K i={Gauge} l="Broker cash" v={m(alpaca?.account?.cashUsd)}/><K i={TrendingUp} l="Open P&L" v={alpaca?m(alpaca.positions.reduce((s,q)=>s+n(q.unrealizedPnlUsd),0)): '—'}/><K i={Activity} l="Broker positions" v={alpaca?alpaca.positions.length:'—'}/><K i={BrainCircuit} l="Recent broker orders" v={alpaca?alpaca.orders.length:'—'}/></section>
   <div className="bot-safety"><ShieldCheck size={18}/><div><strong>Execution and automatic protection not enabled in this dashboard</strong><p>Account data is broker-reported. No buy, sell or stop buttons are available until the dedicated execution and recovery integration is verified.</p></div></div>
   <section className="bot-grid"><article><div className="panel-head"><div><span>BROKER PORTFOLIO</span><h2>Open Alpaca Positions</h2></div><ShieldCheck size={18}/></div>{alpaca?.positions.length?alpaca.positions.map((q,i)=><div className="bot-pos" key={`${q.symbol}-${i}`}><div className="bot-pos-title"><strong>{q.symbol}</strong><span className="bull">{q.side||'long'}</span></div><div className="bot-pos-stats"><span>Quantity<b>{q.quantity??'—'}</b></span><span>Entry<b>{m(q.averageEntryPrice)}</b></span><span>Market<b>{m(q.currentPrice)}</b></span><span>Value<b>{m(q.marketValue)}</b></span><span>Unrealized P&L<b>{m(q.unrealizedPnlUsd)}</b></span></div></div>):<div className="bot-empty">{alpaca?'No open Alpaca crypto positions.':'Awaiting Alpaca data.'}</div>}</article>
   <article><div className="panel-head"><div><span>ALPACA PAPER</span><h2>Recent Broker Orders</h2></div><Activity size={18}/></div>{alpaca?.orders.length?alpaca.orders.slice(0,10).map(q=><div className="bot-order" key={q.id}><div><strong>{q.symbol} · {q.side?.toUpperCase()}</strong><small>{q.status} · {q.type}</small></div><div><b>{q.filledQuantity??0} filled</b><small>{q.submittedAt?new Date(q.submittedAt).toLocaleString(): '—'}</small></div></div>):<div className="bot-empty">{alpaca?'No recent crypto orders.':'Awaiting Alpaca data.'}</div>}</article></section>
  </>:<>
   <div className="bot-provider"><div><strong>INTERNAL SIMULATOR — NOT ALPACA</strong><small>Historical simulator data and existing controls</small></div><span className="simulator">SIMULATED FILLS</span></div>
   <section className="bot-kpis"><K i={WalletCards} l="Simulator equity" v={m(a.equityUsd)}/><K i={Gauge} l="Trading allocation" v={m(a.allocationUsd)}/><K i={TrendingUp} l="Open P&L" v={m(a.unrealizedPnlUsd)}/><K i={Activity} l="Positions" v={`${n(a.openPositions)}/3`}/><K i={BrainCircuit} l="Trade memory" v={records.length}/></section>
   <section className="bot-grid"><article><div className="panel-head"><div><span>SIMULATOR</span><h2>Open Positions</h2></div><ShieldCheck size={18}/></div>{p.length?p.map(q=><div className="bot-pos" key={q.id}><div className="bot-pos-title"><div><strong>{q.symbol}</strong><span className={q.direction==='LONG'?'bull':'bear'}>{d(q.direction)}</span></div><div className="bot-pos-actions"><button onClick={()=>explain(q.id)} disabled={busy===`ex-${q.id}`}><CircleHelp size={14}/>Why this trade?</button><button className="danger" onClick={()=>close(q)} disabled={busy===`close-${q.id}`}><XCircle size={14}/>Close simulator trade</button></div></div><div className="bot-pos-stats"><span>Entry<b>{n(q.entryPrice)}</b></span><span>P&L<b>{m(q.unrealizedPnlUsd)}</b></span><span>Leverage<b>{n(q.leverage)}x</b></span><span>Stop<b>{n(q.stop)}</b></span><span>Trailing<b>{q.trailingActive?'ON':'OFF'}</b></span></div></div>):<div className="bot-empty">No open simulator positions.</div>}</article><article><div className="panel-head"><div><span>LEARNING</span><h2>Historical Trade Memory</h2></div><BrainCircuit size={18}/></div>{records.length?records.slice(-6).reverse().map((r,i)=><div className="memory-row" key={r.tradeId||i}><strong>{r.symbol||'Trade'}</strong><span>{r.outcome||'CLOSED'}</span><b>{m(r.realizedPnlUsd)}</b></div>):<div className="bot-empty">No recorded simulator trades.</div>}</article></section>
  </>}
  {ex&&<Explanation data={ex} onClose={()=>setEx(null)}/>}
 </main></div>
}
function K({i:I,l,v}){return <article><I size={17}/><div><span>{l}</span><strong>{v}</strong></div></article>}
function Explanation({data,onClose}){const snap=data.entrySnapshot,decision=data.entryDirectionDecision;return <div className="explain-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="explain-card"><div className="explain-head"><div><span>RECORDED EVIDENCE</span><h2>{data.symbol} · {d(data.direction)}</h2></div><button onClick={onClose}>×</button></div>{data.evidenceMissing?<div className="explain-warning">Original entry evidence was not stored. No explanation has been fabricated.</div>:<><div className="explain-grid"><E l="Research rank" v={data.researchRankScore}/><E l="Execution rank" v={data.executionRankScore}/><E l="Direction" v={d(decision?.direction||data.direction)}/><E l="Exit reason" v={data.management?.exitReason||'Open position'}/></div><div className="explain-json"><strong>Entry research snapshot</strong><pre>{JSON.stringify(snap,null,2)}</pre></div></>}<div className="explain-json"><strong>Management history</strong><pre>{JSON.stringify(data.consistencyHistory||[],null,2)}</pre></div></section></div>}
function E({l,v}){return <div><span>{l}</span><b>{v??'Unavailable'}</b></div>}
