export const CRYPTO_DIRECTION=Object.freeze({LONG:"LONG",SHORT:"SHORT",NEUTRAL:"NEUTRAL"});
export const CRYPTO_ENGINE_ROLE=Object.freeze({DIRECTIONAL:"DIRECTIONAL",CONTEXT:"CONTEXT",EXECUTION:"EXECUTION",RISK:"RISK",LIFECYCLE:"LIFECYCLE"});
export const CRYPTO_TIME_HORIZON=Object.freeze({SCALP:"SCALP",INTRADAY:"INTRADAY",SWING:"SWING",STRUCTURAL:"STRUCTURAL"});
export const CRYPTO_ENGINE_STATUS=Object.freeze({COMPLETE:"COMPLETE",INSUFFICIENT_DATA:"INSUFFICIENT_DATA",ERROR:"ERROR"});
const finite=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f,clamp=(v,a,b)=>Math.min(b,Math.max(a,finite(v))),round=(v,p=2)=>{const f=10**p;return Math.round(finite(v)*f)/f;};
export function directionFromScore(score,neutralBand=8){const x=clamp(score,-100,100);return x>neutralBand?"LONG":x<-neutralBand?"SHORT":"NEUTRAL";}
export function directionalScoreFromSupports({longSupport=0,shortSupport=0}={}){return round(clamp(finite(longSupport)-finite(shortSupport),-100,100));}
export function buildCryptoDirectionalResult({engine,role=CRYPTO_ENGINE_ROLE.DIRECTIONAL,horizon=CRYPTO_TIME_HORIZON.INTRADAY,status=CRYPTO_ENGINE_STATUS.COMPLETE,longSupport=0,shortSupport=0,confidence=0,quality=null,reasons=[],risks=[],evidence={},neutralBand=8,metadata={}}={}){
 const long=clamp(longSupport,0,100),short=clamp(shortSupport,0,100),directionalScore=directionalScoreFromSupports({longSupport:long,shortSupport:short});
 return{engine:String(engine??"UNKNOWN_ENGINE"),role,horizon,status,direction:directionFromScore(directionalScore,neutralBand),directionalScore,longSupport:round(long),shortSupport:round(short),directionalSeparation:round(Math.abs(long-short)),confidence:round(clamp(confidence,0,1),4),quality:quality==null?null:round(clamp(quality,0,100)),reasons:Array.isArray(reasons)?reasons:[],risks:Array.isArray(risks)?risks:[],evidence:evidence&&typeof evidence==="object"?evidence:{},metadata:metadata&&typeof metadata==="object"?metadata:{},createdAt:new Date().toISOString()};
}
export function buildInsufficientDirectionalResult({engine,role=CRYPTO_ENGINE_ROLE.DIRECTIONAL,horizon=CRYPTO_TIME_HORIZON.INTRADAY,reasons=["INSUFFICIENT_DATA"],evidence={},metadata={}}={}){return buildCryptoDirectionalResult({engine,role,horizon,status:CRYPTO_ENGINE_STATUS.INSUFFICIENT_DATA,longSupport:0,shortSupport:0,confidence:0,quality:null,reasons,evidence,metadata});}
export function buildErroredDirectionalResult({engine,role=CRYPTO_ENGINE_ROLE.DIRECTIONAL,horizon=CRYPTO_TIME_HORIZON.INTRADAY,error,evidence={}}={}){return buildCryptoDirectionalResult({engine,role,horizon,status:CRYPTO_ENGINE_STATUS.ERROR,reasons:[error instanceof Error?error.message:String(error??"UNKNOWN_ERROR")],evidence});}
export function isDirectionalResult(v){return Boolean(v&&typeof v==="object"&&typeof v.engine==="string"&&Object.values(CRYPTO_ENGINE_ROLE).includes(v.role)&&Object.values(CRYPTO_TIME_HORIZON).includes(v.horizon)&&Object.values(CRYPTO_ENGINE_STATUS).includes(v.status)&&Object.values(CRYPTO_DIRECTION).includes(v.direction)&&Number.isFinite(Number(v.directionalScore))&&Number.isFinite(Number(v.longSupport))&&Number.isFinite(Number(v.shortSupport))&&Number.isFinite(Number(v.confidence)));}
export default{CRYPTO_DIRECTION,CRYPTO_ENGINE_ROLE,CRYPTO_TIME_HORIZON,CRYPTO_ENGINE_STATUS,directionFromScore,directionalScoreFromSupports,buildCryptoDirectionalResult,buildInsufficientDirectionalResult,buildErroredDirectionalResult,isDirectionalResult};
