const ErrorCode = {
  "description": "Error code\n\n`unknown_error` `invalid_request_uri` `invalid_request_object` `consent_required` `interaction_required` `login_required` `request_unauthorized` `request_forbidden` `invalid_request` `unauthorized_client` `access_denied` `unsupported_response_type` `unsupported_response_mode` `invalid_scope` `server_error` `temporarily_unavailable` `unsupported_grant_type` `invalid_grant` `invalid_client` `not_found` `invalid_state` `misconfiguration` `insufficient_entropy` `invalid_token` `token_signature_mismatch` `scope_not_granted` `token_claim` `token_inactive` `request_not_supported` `request_uri_not_supported` `jti_known` `quota_exceeded` `conflict`",
  "enum": [
    "unknown_error",
    "invalid_request_uri",
    "invalid_request_object",
    "consent_required",
    "interaction_required",
    "login_required",
    "request_unauthorized",
    "request_forbidden",
    "invalid_request",
    "unauthorized_client",
    "access_denied",
    "unsupported_response_type",
    "unsupported_response_mode",
    "invalid_scope",
    "server_error",
    "temporarily_unavailable",
    "unsupported_grant_type",
    "invalid_grant",
    "invalid_client",
    "not_found",
    "invalid_state",
    "misconfiguration",
    "insufficient_entropy",
    "invalid_token",
    "token_signature_mismatch",
    "scope_not_granted",
    "token_claim",
    "token_inactive",
    "request_not_supported",
    "request_uri_not_supported",
    "jti_known",
    "quota_exceeded",
    "conflict"
  ],
  "type": "string",
  "title": "error_code",
  "x-readme-ref-name": "error_code"
} as const;
export default ErrorCode
